POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "hassan1",
  "password": "Mahdi123"
}

###
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2RjYzY2YzdkOTFmYjRhM2QzZTQ1ZiIsImlhdCI6MTc0MTU0MDQ1NCwiZXhwIjoxNzQ0MTMyNDU0fQ.BAaSq_cy02pfQYwKpPr43EbeHnga8v44wWaF2h90NUY
